### ISSUE TITLE
Mixed Content Over HTTPS

### ISSUE THREAD

**Issue by un1r8okq** [csloisel/is-gallow-front#1]
When using https, Google Chrome blocks the JSON request because the page is requesting mixed https and http content.
The bug can be fixed by changing `http://www.reddit.com/r/all/.json?limit=50` to `https://www.reddit.com/r/all/.json?limit=50`.
If you wanted to still pure http support, you could use `window.location.protocol` to see which protocol your page is currently being served over.

**Comment by csloisel** [comment]
I wonder if jQuery has any protocol handling if it is omitted.

**Comment by un1r8okq** [comment]
Setting it to `https://` should solve this problem over all protocols. I can't see the problem with AJAXing https content from an http page, it's `https` -> `http` that browsers don't like.

**Comment by Viper007Bond** [comment]
This was fixed in #3.

**Comment by un1r8okq** [comment]
This wasn't fixed because the HTTPS link still doesnt work.
https://csloisel.github.io/is-gallow-front/

**Comment by csloisel** [comment]
Forgot to push updates to the page branch, should be fixed.
